### ISSUE TITLE
[bug] build error

### ISSUE THREAD

**Issue by LincZero** [Otto-J/Obsidian-Vue-Starter#2]
## build error

![image](https://github.com/user-attachments/assets/cf2c9f35-5d99-42f3-a71e-7dd8687de4fc)

## version:

This problem occurred in github codespace, I had exactly the same problem with my own windows environment

```bash
$ cnpm -v
cnpm@9.4.0 (/usr/local/share/nvm/versions/node/v20.17.0/lib/node_modules/cnpm/lib/parse_argv.js)
npm@9.9.2 (/usr/local/share/nvm/versions/node/v20.17.0/lib/node_modules/cnpm/node_modules/npm/index.js)
node@20.17.0 (/usr/local/share/nvm/versions/node/v20.17.0/bin/node)
npminstall@7.12.0 (/usr/local/share/nvm/versions/node/v20.17.0/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
prefix=/usr/local/share/nvm/versions/node/v20.17.0 
linux x64 6.5.0-1025-azure 
registry=https://registry.npmmirror.com
```

**Comment by LincZero** [comment]
Update dependency packages still have build errors

![image](https://github.com/user-attachments/assets/66907bba-4fb4-42c4-aabe-0a48f07e94c3)

**Comment by LincZero** [comment]
I use https://github.com/guopenghui/obsidian-vue-starter, can the normal build

**Comment by LincZero** [comment]
不对，那个github codespace上能跑，我电脑跑不了。

依赖都太旧太多冲突和其他问题了……

**Comment by LincZero** [comment]
在obsidian-vue-starter基础上修改了一些依赖版本，再把hello.tsx删了，看起来构建比较稳定了

![image](https://github.com/user-attachments/assets/e60fa3e0-6074-466b-a4f3-88d5839d1eda)

**Comment by Otto-J** [comment]
好
